name : Building Block Example

on:
  push:
    branches:
      - main

jobs:
    echo-hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Hello World
              run: ${{ github.event_name }} Hello World
   