name : Building Block Example
on:
  push:
    branches:
      - main

jobs:
  echo-check-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print timestamp
        run: $(date +\"%Y-%m-%d %H:%M:%S\")"

   