name: 01-first-workflow
on:
    workflow_dispatch:
    # push:
    #     branches:
    #         - development

jobs:
    failed-job:
        runs-on: ubuntu-latest
        steps:
            - run: exit 0
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world !!"