name: 01-first-workflow
on:
    push:
        branches:
            - development

jobs:
    failed-job:
        runs-on: ubuntu-latest
        steps:
            - run: | 
                exit 1
    echo-hello:
        needs: failed-job
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world !!"