name : 04-using-actions
on: [push]
defaults:
    run:
        working-directory: react-app
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              
            - name : setup the node
              uses: actions/setup-node@v3
              with:
                    node-version: '22.x'
            - name: Install dependencies
              run: npm ci
             
            - name : run unit tests
              run: npm test
             