name: 06-using-action
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
        defaults:
            run:
                working-directory: react-app
    deploy:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: react-app
        steps:
            - name : checkout
              uses: actions/checkout@v4
            - name : install node
              uses: actions/setup-node@v4
              with:
                node-version: '24'
            - name: check node version
              run: node -v
            - name: install dependencies
              run: npm install
            - name: build application
              run: npm run build