name : experssions 
on: 
   workflow_dispatch
jobs:
    echo-check-trigger:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Print trigger event
              run: echo "i was trigger by ${{github.event_name}} event"