name : experssions 
on: 
    push:
        branches:
            - main
    pull_request:
        branches:   
            - main
jobs:
    echo-check-trigger:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Print timestamp
              run: echo "i was trigger by ${{github.event_name}} event"