name : control execution workflow 
on: 
    workflow_dispatch:
        inputs:
            pass-unit-test:
                type: boolean
                description: wether unit test will pass or not
                default: true

    push:
       
jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name : lint and test
              run : echo "this is lint and test stage"
    unit-test:
         runs-on: ubuntu-latest
         steps:
            - name : unit test
              run : echo "this is unit test stage"
            - name: failing test 
              if: ${{ github.event.inputs.pass-unit-test == 'true' }}
              run : exit 1

    deploy-nonprod:
         runs-on: ubuntu-latest
         needs:
            - lint-build
            - unit-test
         steps:
                - name : deploy non prod
                  run : echo "this is deploy non prod stage"
    e2e-test:
         runs-on: ubuntu-latest
         needs: deploy-nonprod
         steps:
            - name : e2e test
              run : echo "this is e2e test stage"
    deploy-prod:
         runs-on: ubuntu-latest
         needs: e2e-test
         steps:
            - name : deploy prod
              run : echo "this is deploy prod stage"

