name : 10-working-with-inputs
on: 
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: "skip deployment and only print outputs"
                default: false
            target:
                type: environment
                description: "target environment"
            tag:
                type: choice
                description: "tag to deploy"
                default: v1
                options: 
                    - v1
                    - v2

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build
              run: echo "Building...with tag ${{inputs.tag}}"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ !inputs.dry-run }}
        steps:
            - name: deploy
              run: echo "Deploying...to target ${{inputs.target}} with tag ${{inputs.tag}}"


