name: 13-caching
on: 
    push:
        branches: 
            - main
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                description: "use cache"
                default: true
defaults:
   run: 
         working-directory: react-app

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name : setup the node
              uses: actions/setup-node@v3
              with:
                    node-version: '22.x'
            - name : install dependencies
              run: npm ci
                
    build:
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            - name : build the application
              run: npm run build 
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: run unit tests
              run: npm run test
       