name: 14-artifact
on: 
    push:
        branches: 
            - main
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                description: "use cache"
                default: true
defaults:
    run: 
        working-directory: react-app
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name : checkout code
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3.5.1
              with:
                    node-version: '22.x'  
                    cache: 'npm' 
                    cache-dependency-path: react-app/package-lock.json
            - name : cache
              uses: actions/cache@v4
              id: cache
              with:
                path: react-app/node_modules
                key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                        ${{ runner.os }}-node-modules-
            - name: install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name : test the code 
              run : npm run test
            - name : build the code
              run : npm run build
            - name : upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: react-app-build
                path: react-app/build
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name : download artifact
              uses: actions/download-artifact@v4
              with:
                   name: react-app-build
                   path: react-app/build
            - name : show dir structure
              run: ls -R react-app

