name : metrics in github actions
on: 
    workflow_dispatch: 
jobs:
    backwords_compatibility:
      name : ${{ matrix.node-version }} on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      
      strategy:
          fail-fast: false
          matrix:
              node-version: [16.x,18.x,20.x]
              os: [ubuntu-latest, windows-latest]
      steps:
        - name: setup node
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - name : perform some steps
          run: |
              echo "node version is ${{ matrix.node-version }}"
              echo "os is ${{ matrix.os }}"
              echo "hello world"
    include-example:
        name : ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                color: [red, green]
                shape: [circle, square]
                size: [small, large]
                include:
                  - color: red
                    shape: triangle
                exclude:
                  - color: green
                    shape: square
        steps:
            - name: sdummy step
              run: |
                echo "size is ${{ matrix.size }}"
               
               