name: 17-composite actions 
on :
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                description: "use cache"
                default: true
env: 
    working-directory: react-app
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v3
            - name : build and setup the node environment
              uses: './.github/actions/composite-cache-dep'
              with:
                node-version: 16.x
                working-directory: react-app

            